### ISSUE TITLE
Floor price is incorrect when using Opensea asset endpoint

### ISSUE THREAD

**Issue by chillerno1** [chillerno1/discord-nft-satellite#1]
The Opensea asset endpoint is incorrectly returning 0 for the floor price of some collections. This seems to be an issue with the 'stats' metadata appended from the collection when using an asset URL. The issue is not present when calling the collection api directly. 

Example BAYC 
URL: https://api.opensea.io/api/v1/asset/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/995
```        
'stats': {
            'one_day_volume': 437.431,
           ...
            'num_reports': 38,
            'market_cap': 428579.5047619047,
            'floor_price': 0
        },
```

Calling the collection directly: https://api.opensea.io/collection/boredapeyachtclub
```
'stats': {
            'one_day_volume': 437.431,
           ...
            'num_reports': 38,
            'market_cap': 428579.5047619047,
            'floor_price': 32.0
        },
```

I will be swapping over to the collection endpoint to resolve this.

**Comment by GoldLiondev** [comment]
Hello, I got the same issue to use Opeansea collections endpoint.
They always return 0 for floor price. but it is incorrect and when I get the floor price via opensea stats endpoint, it return correct price.
please help me how to fix it asap.
Thanks

**Comment by LucasDcarprio** [comment]
good day , same issues .
catch a wrong floor price , its not same as floor price as website shows
